# Site settings
title: "Optiker Kirchzarten: Gut sehen, Gut aussehen! Sehgut-Optik"
email: kontakt@sehgut-optik.de
author: Elvira Dilger
description: "&#10164; Bahnhofstr. 8 &#9742; 07661/9691926 Persönliche Beratung und individuelle Brillen von Joshi, Julbo, Morel und Götti. Ihr Optiker in Kirchzarten."
url: "https://sehgut-optik.de"
timezone: Europe/Berlin
language: de_DE

# Build settings
permalink: :title/
sass:
  sass_dir: css
include: [.htaccess]

# Social icons
show_social_icons: false
github_username: someGithubUser
twitter_username: someTwitterUser

# Plugins

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag