# Site settings
title: "DMFK 2020 - Es gibt Bein!"
email: info@dmfk2020.de
author: FKK Freiburg
description: "Das wichtigste in 160 Zeichen…"
url: "https://dmfk2020.de"
timezone: Europe/Berlin
language: de_DE

# Build settings
permalink: :title/
sass:
  sass_dir: css
include: [.htaccess]
exclude: [yarn.lock, robots.txt, package.json, .DS_Store]

# Social icons
show_social_icons: false
github_username: someGithubUser
twitter_username: someTwitterUser

# Plugins

plugins:
  # - jekyll-sitemap
  - jekyll-seo-tag