# Site settings
title: "DMFK 2020 - Es gibt Bein!"
email: info@dmfk2020.de
author: FKK Freiburg
description: "Das wichtigste in 160 Zeichen…"
url: "https://dmfk2020.de"
timezone: Europe/Berlin
language: de_DE

# Build settings
permalink: :title/
sass:
  sass_dir: css
include: [.htaccess]
exclude: [.jekyll-cache, yarn.lock, robots.txt, package.json, .DS_Store]

# Social icons
show_social_icons: false
facebook_username: someTwitterUser
instragram_username: dmfk2020

# Plugins

plugins:
  # - jekyll-sitemap
  - jekyll-seo-tag